# ==========================================
# Builder
# ==========================================

FROM node:24-bookworm-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

# Prisma configuration
COPY prisma.config.ts ./
COPY prisma ./prisma

RUN npx prisma generate --config ./prisma.config.ts

# TypeScript configuration
COPY tsconfig.json ./

# Source code
COPY src ./src

# Build application
RUN npm run build


# ==========================================
# Production
# ==========================================

FROM node:24-bookworm-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

# Create production dependencies
COPY package*.json ./

RUN npm ci --omit=dev \
    && npm cache clean --force

# Application
COPY --from=builder /app/dist ./dist

# Prisma generated client
COPY --from=builder /app/src/generated ./src/generated

# Prisma schema/config
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

USER node

CMD ["node", "dist/server.js"]