# ==========================================
# Builder
# ==========================================

FROM node:24-bookworm-slim AS builder

WORKDIR /app


# ==========================================
# System Dependencies
# ==========================================

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl \
    && rm -rf /var/lib/apt/lists/*


# ==========================================
# Dependencies
# ==========================================

COPY package*.json ./

RUN npm ci


# ==========================================
# Prisma
# ==========================================

COPY prisma.config.ts ./
COPY prisma ./prisma


# ==========================================
# Configuration
# ==========================================

COPY tsconfig.json ./


# ==========================================
# Source
# ==========================================

COPY src ./src


# ==========================================
# Prisma Client
# ==========================================

ENV DATABASE_URL="postgresql://postgres:postgres@localhost:5432/dummy"

RUN npm run prisma:generate


# ==========================================
# Build
# ==========================================

RUN npm run build


# ==========================================
# Production
# ==========================================

FROM node:24-bookworm-slim AS runner

WORKDIR /app

ENV NODE_ENV=production


# ==========================================
# System Dependencies
# ==========================================

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl \
    && rm -rf /var/lib/apt/lists/*


# ==========================================
# Production Dependencies
# ==========================================

COPY package*.json ./

RUN npm ci --omit=dev \
    && npm cache clean --force


# ==========================================
# Application
# ==========================================

COPY --from=builder /app/dist ./dist


# ==========================================
# Prisma Generated Client
# ==========================================

COPY --from=builder /app/src/generated ./src/generated


# ==========================================
# Prisma Configuration
# ==========================================

COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/prisma ./prisma


# ==========================================
# Security
# ==========================================

USER node


# ==========================================
# Application
# ==========================================

EXPOSE 3000

CMD ["node", "dist/server.js"]